version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:20.8.1

jobs:
  code-checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: 'Install dependencies'
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys
      - run: ./scripts/circleci-pre-run.sh
      - deploy:
          command: npm run release

workflows:
  version: 2

  publish:
    jobs:
      - code-checkout:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - code-checkout
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
